list: $/mavitm/content/models/post/columns.yaml
modelClass: Mavitm\Content\Models\Post
title: Posts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'mavitm/content/posts/update/:id'
